# Generated by Django 3.0.5 on 2024-07-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240715_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
