# Generated by Django 3.0.14 on 2024-07-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
