# Generated by Django 3.2.23 on 2024-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20240727_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='work_status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
