# Generated by Django 3.2.23 on 2024-07-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payemnt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payemnt',
            table='Payemnt',
        ),
    ]
