# Generated by Django 3.2.23 on 2024-07-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_payemnt_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payemnt',
            new_name='Payment',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='Payment',
        ),
    ]
