from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [

    path("/",views.login),
    path("/login_post",views.login_post),
    path("/changepassword",views.changepassword),
    path("/change_pswrdpost",views.change_pswrdpost),
    path("/addpolice",views.addpolice),
    path("/addpolice_post", views.addpolice_post),
    path("/viewpolice", views.viewpolice),
    path("/searchpolice", views.searchpolice),
    path("/deletepolice/<id>", views.deletepolice),
    path("/editpolice/<id>", views.editpolice),
    path("/editpolice_post", views.editpolice_post),
    path("/addnotification",views.addnotification),
    path("/addnotification_post", views.addnotification_post),
    path("/viewnotification", views.viewnotification),
    path("/searchnotification", views.searchnotification),
    path("/deletenotification/<id>", views.deletenotification),
    path("/editnotification/<id>", views.editnotification),
    path("/editnotification_post", views.editnotification_post),
    path("/viewlabour1",views.viewlabour1),
    path("/aaprovelabor/<id>",views.aaprovelabor),
    path("/rejectlabor/<id>",views.rejectlabor),
    path("/viewlabour",views.viewlabour),
    path("/viewcriminallist",views.viewcriminallist),
    path("/searchcriminal",views.searchcriminal),
    path("/viewcomplaint",views.viewcomplaint),
    path("/viewfeedback",views.viewfeedback),
    path("/searchfeedback",views.searchfeedback),


#     ===================================
    path("/home1",views.home1),
    path("/addcriminallist",views.addcriminallist),
    path("/addcriminallist_post",views.addcriminallist_post),
    path("/viewcriminal1",views.viewcriminal1),
    path("/searchcriminal1",views.searchcriminal1),
    path("/deletecriminal/<id>",views.deletecriminal),
    path("/editcriminallist/<id>", views.editcriminallist),
    path("/editcriminallist_post",views.editcriminallist_post),
    path("/addlabour",views.addlabour),
    path("/addlabour_post",views.addlabour_post),
    path("/viewlabour1",views.viewlabour1),
    path("/viewapprovedlabour",views.viewapprovedlabour),
    path("/blocklabor/<id>",views.blocklabor),
    path("/deletelabour/<id>",views.deletelabour),
    path("/editlabour/<id>",views.editlabour),
    path("/editlabour_post",views.editlabour_post),
    path("/viewcomplaint1",views.viewcomplaint1),
    path("/addreply/<id>",views.addreply),
    path("/addreply_post",views.addreply_post),
    path("/viewnotification1",views.viewnotification1),
    path("/viewfeedback1",views.viewfeedback1),
    path("/searchfeedback1",views.searchfeedback1),
    path("/changepassword1", views.changepassword1),
    path("/change_pswrdpost1", views.change_pswrdpost1),
#     -----------------------android--------------------

    path("/and_login",views.and_login),
    path("/and_usersignup",views.and_signup),
    path("/and_changepassword",views.and_changepassword),
    path("/and_labchangepassword",views.and_labchangepassword),
    path('/and_viewprofile', views.and_viewprofile, name='and_viewprofile'),
    path('/and_edit_prof', views.and_edit_prof, name='and_edit_prof'),
    path('/and_editprofile', views.and_editprofile, name='and_editprofile'),
    path('/and_sendcomplaint', views.and_sendcomplaint, name='and_sendcomplaint'),
    path('/and_sendfeedback', views.and_sendfeedback, name='and_sendfeedback'),
    path('/and_view_reply', views.and_view_reply, name='and_view_reply'),
    path('/and_labview_reply', views.and_labview_reply, name='and_labview_reply'),
    path('/and_view_labour', views.and_view_labour, name='and_view_labour'),
    path('/and_view_labour_by_id', views.and_view_labour_by_id, name='and_view_labour_by_id'),
    path('/and_view_labour_search', views.and_view_labour_search, name='and_view_labour_search'),
    # path('/and_addreport', views.and_addreport, name='and_addreport'),
    path('/and_sendrequest', views.and_sendrequest, name='and_sendrequest'),
    # path('/and_viewemployee', views.and_viewemployee, name='and_viewemployee'),
    # path('/and_viewemployee_search', views.and_viewemployee_search, name='and_viewemployee_search'),
    # path('/and_searchemployee', views.and_searchemployee, name='and_searchemployee'),
    # path('/and_sendrequest1', views.and_sendrequest1, name='and_sendrequest1'),
    # path('/and_viewwageplan', views.and_viewwageplan, name='and_viewwageplan'),
    path('/and_view_skill', views.and_view_skill, name='and_view_skill'),
    # path('/and_send_reviewtocontractor', views.send_reviewtocontractor, name='send_reviewtocontractor'),
    # path('/and_view_reviewcustom', views.view_reviewcustom, name='view_reviewcustom'),
    path('/send_reviewtoworker', views.send_reviewtoworker, name='send_reviewtoworker'),
    path('/and_lab_signup', views.and_lab_signup, name='and_lab_signup'),
    path('/and_lab_changepassword', views.and_lab_changepassword, name='and_lab_changepassword'),
    path('/and_lab_viewprofile', views.and_lab_viewprofile, name='and_lab_viewprofile'),
    path('/and_lab_editpro', views.and_lab_editpro, name='and_lab_editpro'),
    path('/and_lab_editprofile', views.and_lab_editprofile, name='and_lab_editprofile'),
    path('/and_lab_viewrequest', views.and_lab_viewrequest, name='and_lab_viewrequest'),
    path('/and_cust_viewrequest', views.and_cust_viewrequest, name='and_cust_viewrequest'),
    path('/and_lab_editskill', views.and_lab_editskill, name='and_lab_editskill'),
    path('/and_lab_addskill', views.and_lab_addskill, name='and_lab_addskill'),
    path('/and_lab_viewskill', views.and_lab_viewskill, name='and_lab_viewskill'),
    path('/and_lab_edit_skill', views.and_lab_edit_skill, name='and_lab_edit_skill'),
    path('/and_lab_editskilma', views.and_lab_editskilma, name='and_lab_editskilma'),
    # path('/and_lab_sendcomplaint', views.and_lab_sendcomplaint, name='and_lab_sendcomplaint'),
    # path('/and_lab_viewworkreview', views.and_lab_viewworkreview, name='and_lab_viewworkreview'),
    # path('/and_view_type', views.and_view_type, name='and_view_type'),

    path('/and_view_review', views.and_view_review, name='and_view_review'),
    path('/deleteskill', views.deleteskill, name='deleteskill'),
    path('/approve_request', views.approve_request, name='approve_request'),
    path('/reject_request', views.reject_request, name='reject_request'),
    path('/update_work_status', views.update_work_status, name='update_work_status'),
    path('/payment', views.payment, name='payment'),
    path('/and_view_payment', views.and_view_payment, name='and_view_payment'),









]